# create databases
CREATE DATABASE IF NOT EXISTS `_system_db`;
CREATE DATABASE IF NOT EXISTS `_local_shop`;
CREATE DATABASE IF NOT EXISTS `_s3_db`;
CREATE DATABASE IF NOT EXISTS `_sns_db`;

# create db for tenacy
CREATE DATABASE IF NOT EXISTS `shop1`;
CREATE DATABASE IF NOT EXISTS `shop2`;
CREATE DATABASE IF NOT EXISTS `shop3`;
CREATE DATABASE IF NOT EXISTS `shop4`;
CREATE DATABASE IF NOT EXISTS `shop5`;
CREATE DATABASE IF NOT EXISTS `shop6`;
CREATE DATABASE IF NOT EXISTS `shop7`;
CREATE DATABASE IF NOT EXISTS `shop8`;
CREATE DATABASE IF NOT EXISTS `shop9`;
CREATE DATABASE IF NOT EXISTS `shop10`;